# Generated by Django 3.0.6 on 2020-07-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=120)),
                ('district_added_date', models.DateField(auto_now_add=True)),
                ('district_updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idol_name', models.CharField(max_length=120)),
                ('idol_gender', models.CharField(max_length=120)),
                ('idol_added_date', models.DateField(auto_now_add=True)),
                ('idol_updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=120)),
                ('state_added_date', models.DateField(auto_now_add=True)),
                ('state_updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temple_name', models.CharField(max_length=120)),
                ('temple_status', models.CharField(default='Active', max_length=120)),
                ('temple_description', models.TextField(blank=True, max_length=200, null=True)),
                ('temple_place', models.CharField(max_length=120)),
                ('temple_city', models.CharField(max_length=120)),
                ('temple_PINCode', models.IntegerField()),
                ('temple_image', models.ImageField(upload_to='pics', verbose_name='IMAGE')),
                ('temple_icon', models.ImageField(upload_to='pics', verbose_name='IMAGE')),
                ('temple_mail', models.CharField(max_length=120)),
                ('temple_phone', models.CharField(max_length=20)),
                ('temple_added_date', models.DateField(auto_now_add=True)),
                ('temple_updated_date', models.DateField(auto_now=True)),
                ('temple_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Temple.District')),
                ('temple_main_idol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Temple.Idols')),
                ('temple_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Temple.State')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Temple.State'),
        ),
    ]
