# Generated by Django 3.0.6 on 2020-07-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Temple', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_category_name', models.CharField(max_length=120)),
                ('offering_type', models.CharField(max_length=120)),
                ('offering_category_added_date', models.DateField(auto_now_add=True)),
                ('offering_category_updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offerings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_name', models.CharField(max_length=120)),
                ('offering_added_date', models.DateField(auto_now_add=True)),
                ('offering_updated_date', models.DateField(auto_now=True)),
                ('offering_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offerings.OfferingCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Temple_Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_price', models.IntegerField()),
                ('prasadam_needed', models.BooleanField(default=True)),
                ('offering_details_added_date', models.DateField(auto_now_add=True)),
                ('offering_details_updated_date', models.DateField(auto_now=True)),
                ('offering_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Offerings.Offerings')),
                ('offering_temple_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Temple.Temple')),
            ],
        ),
    ]
